# SPDX-License-Identifier: CC0-1.0
%YAML 1.1
---
version: 1
algorithms:
  - BlackLevel:
      blackLevel: 4096
  - Awb:
  - Ccm:
      ccms:
        - ct: 6500
          ccm: [ 1, 0, 0,
                 0, 1, 0,
                 0, 0, 1 ]
  - Adjust:
      gamma: 2.0
      contrast: 1.1
      saturation: 1.25
      sharpness: 1.0
  - Agc:
      target: 2.0
      highlightQuantile: 0.98
      highlightTarget: 0.95
...
